### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by arlejeun** [auth0-blog/vimeo-embed#1]
I'm trying this component but it doesn't work for Mobile support (iPhone6). 
Do you have any plan to make this component mobile ready in the future?

**Comment by unicodeveloper** [comment]
Hello @arlejeun There are no plans to make this mobile ready in the future. This component was built for this [tutorial](https://auth0.com/blog/web-components-how-to-craft-your-own-custom-components/)

**Comment by arlejeun** [comment]
Thanks for the update. I've never done it this way so it's a very interesting tutorial to learn how to develop custom elements.
I just have a quick question. I'm using Polymer 1.8.1 and I thought with the webcomponent.js polyfill I would be able to see it with mobile browser, Firefox or IE11 but none of them are working. Only desktop Chrome is working ok. I haven't tried to change the Firefox settings as described in your tutorial but I was wondering if it was something misconfigured on my side for mobile browser. Any idea?
